# Generated by Django 5.1.3 on 2024-11-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='community_vote_distribution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='投票分布'),
        ),
    ]
