# Generated by Django 5.1.3 on 2024-11-23 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_community_vote_distribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlog',
            name='selected_choice_key',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='選択された選択肢キー'),
        ),
        migrations.CreateModel(
            name='QuestionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='試行回数')),
                ('correct_attempts', models.PositiveIntegerField(default=0, verbose_name='正解回数')),
                ('incorrect_attempts', models.PositiveIntegerField(default=0, verbose_name='不正解回数')),
                ('common_wrong_choices', models.JSONField(default=dict, verbose_name='よく間違える選択肢')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='関連する問題')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.JSONField(default=dict, verbose_name='進捗データ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='試験終了フラグ')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question', verbose_name='現在の問題')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='関連試験')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
