# Generated by Django 5.1.3 on 2024-11-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answerlog_selected_choice_key_questionperformance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.JSONField(blank=True, default=list, verbose_name='解説'),
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='キーワード'),
        ),
        migrations.AddField(
            model_name='question',
            name='page_images',
            field=models.JSONField(blank=True, default=list, verbose_name='関連画像ファイル名'),
        ),
    ]
