# Generated by Django 5.1.3 on 2024-11-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_explanation_question_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_en',
            field=models.JSONField(blank=True, default=list, verbose_name='解説（英語）'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_ja',
            field=models.JSONField(blank=True, default=list, verbose_name='解説（日本語）'),
        ),
    ]
