# Generated by Django 5.1.3 on 2024-12-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, help_text='OCR対象の画像ファイルパス（ユニークにして二重実行を回避できる）', max_length=500, null=True, unique=True)),
                ('vision_api_response', models.JSONField(blank=True, help_text='Vision APIのレスポンスをまるっと保持', null=True)),
                ('full_text', models.TextField(blank=True, help_text='textAnnotations[0].description', null=True)),
                ('avg_confidence', models.FloatField(default=0.0, help_text='wordレベル平均confidence')),
                ('status', models.CharField(default='pending', help_text='OCR実行状態: pending|done|errorなど', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Vision APIエラーなど発生時のメッセージ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
