# Generated by Django 5.1.3 on 2024-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_ocrresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='normalized_text',
            field=models.TextField(blank=True, help_text='ノーマライズ済みテキスト', null=True),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Vision APIエラー発生時のメッセージ', null=True),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='full_text',
            field=models.TextField(blank=True, help_text='textAnnotations[0].description など全文', null=True),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='status',
            field=models.CharField(default='pending', help_text='OCR実行状態: pending|done|error など', max_length=50),
        ),
    ]
