# Generated by Django 5.1.3 on 2024-12-29 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='試験識別キー')),
                ('name', models.CharField(max_length=255, verbose_name='試験名')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='試験メタデータ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '汎用試験',
                'verbose_name_plural': '汎用試験一覧',
            },
        ),
        migrations.CreateModel(
            name='QuestionCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='問題画像一覧')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='問題メタデータ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_core.examcore', verbose_name='関連試験')),
            ],
            options={
                'verbose_name': '汎用問題',
                'verbose_name_plural': '汎用問題一覧',
            },
        ),
        migrations.CreateModel(
            name='ChoiceCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='選択肢ラベル')),
                ('text', models.TextField(verbose_name='選択肢本文')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='選択肢画像一覧')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解フラグ')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='選択肢メタデータ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exam_core.questioncore', verbose_name='関連する問題')),
            ],
            options={
                'verbose_name': '汎用選択肢',
                'verbose_name_plural': '汎用選択肢一覧',
            },
        ),
        migrations.CreateModel(
            name='AnswerLogCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解かどうか')),
                ('response_time', models.DurationField(blank=True, null=True, verbose_name='解答時間')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='回答メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_core.choicecore', verbose_name='選択された選択肢')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_core.examcore', verbose_name='関連試験')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_core.questioncore', verbose_name='関連問題')),
            ],
            options={
                'verbose_name': '汎用回答ログ',
                'verbose_name_plural': '汎用回答ログ一覧',
            },
        ),
        migrations.AddIndex(
            model_name='questioncore',
            index=models.Index(fields=['exam'], name='exam_core_q_exam_id_583486_idx'),
        ),
        migrations.AddIndex(
            model_name='choicecore',
            index=models.Index(fields=['question'], name='exam_core_c_questio_da6df5_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlogcore',
            index=models.Index(fields=['user', 'exam'], name='exam_core_a_user_id_7f6b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlogcore',
            index=models.Index(fields=['question'], name='exam_core_a_questio_ac292d_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlogcore',
            index=models.Index(fields=['choice'], name='exam_core_a_choice__842a34_idx'),
        ),
    ]
