# Generated by Django 5.1.3 on 2024-12-30 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='試験カテゴリSLUG')),
                ('name', models.CharField(max_length=255, verbose_name='試験カテゴリ名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
            ],
        ),
        migrations.AddField(
            model_name='examcore',
            name='category',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam_core.examcategory', verbose_name='試験カテゴリ'),
        ),
    ]
