# Generated by Django 5.1.3 on 2024-12-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_core', '0002_examcategory_examcore_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcategory',
            options={'verbose_name': '試験カテゴリ', 'verbose_name_plural': '試験カテゴリ一覧'},
        ),
        migrations.AddField(
            model_name='questioncore',
            name='question_no',
            field=models.PositiveIntegerField(default=0, help_text='各試験内でユニークになるよう管理する', verbose_name='問題番号'),
        ),
        migrations.AlterUniqueTogether(
            name='questioncore',
            unique_together={('exam', 'question_no')},
        ),
    ]
